### ISSUE TITLE
Xmind crack unwork

### ISSUE THREAD

**Issue by Jason-JP-Yang** [qy527145/crack#3]
Xmind-for-Windows-x64bit-24.10.01101-202410202317.exe 
after run the crack python file, replace asar with a new one, the software not work at all

**Comment by zy1acg** [comment]
Traceback (most recent call last):
  File "E:\crack-main\crack-main\src\crack\base.py", line 104, in run
    self.logger.info("Starting license generation process")
    ^^^^^^^^^^^
AttributeError: 'XmindKeyGen' object has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\crack-main\crack-main\src\crack\xmind\xmind.py", line 92, in <module>
    XmindKeyGen().run()
  File "E:\crack-main\crack-main\src\crack\base.py", line 135, in run
    self.logger.error(f"License generation process failed: {e}")
    ^^^^^^^^^^^
AttributeError: 'XmindKeyGen' object has no attribute 'logger'
